## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [4]:
!nvidia-smi

Sun Jan 29 14:18:52 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 528.24       Driver Version: 528.24       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   41C    P0     5W /  40W |      0MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [7]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.0


## Introduction to Tensors

### Creating tensors

In [8]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [9]:
scalar.ndim

0

In [12]:
scalar.item()
print(type(scalar.item()))
print(type(scalar))

<class 'int'>
<class 'torch.Tensor'>


In [13]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [14]:
vector.ndim

1

In [25]:
print(vector.shape)
print(type(vector.shape))
print(vector.shape[0], type(vector.shape[0]))


torch.Size([2])
<class 'torch.Size'>
2 <class 'int'>


In [26]:
# Matrix
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [30]:
MATRIX.ndim

2

In [33]:
print(MATRIX.shape)
print(type(MATRIX.shape))
print(MATRIX.shape[0], MATRIX.shape[1], type(MATRIX.shape[0]))

torch.Size([2, 2])
<class 'torch.Size'>
2 2 <class 'int'>


In [36]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [4,6,7], [8,9,10]], [[11, 12, 13], [14,16,17], [18,19,20]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  6,  7],
         [ 8,  9, 10]],

        [[11, 12, 13],
         [14, 16, 17],
         [18, 19, 20]]])

In [37]:
TENSOR.ndim

3

In [38]:
TENSOR.shape

torch.Size([2, 3, 3])

In [39]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 4,  6,  7],
        [ 8,  9, 10]])

In [40]:
TENSOR[1]

tensor([[11, 12, 13],
        [14, 16, 17],
        [18, 19, 20]])