# Chapter 3: Pytorch Tensors

### Python Lists

In [1]:
a = [1.0, 2.0, 1.0]
a[2] = 3.0
a

[1.0, 2.0, 3.0]

## 3.1 Constructing tensors

In [2]:
import torch

In [3]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [4]:
a[1]

tensor(1.)

In [5]:
float(a[1])

1.0

In [6]:
a[2] = 2.0
a

tensor([1., 1., 2.])

## 3.2 Anatomy of tensors

Example: store 3 vertices of coords (4,1), (5,3) and (2,1) using a 1D tensor with even-indexes for x and odd-indexes for y coordinate.

In [7]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [8]:
points2 = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points2

tensor([4., 1., 5., 3., 2., 1.])

In [9]:
points == points2

tensor([True, True, True, True, True, True])

In [10]:
points - points2 == torch.zeros(6)

tensor([True, True, True, True, True, True])

In [11]:
points + points2 == 2*points2

tensor([True, True, True, True, True, True])

First coord:

In [12]:
float(points[0]), float(points[1])

(4.0, 1.0)

Storing the coords as a 2D tensor:

In [13]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

To know about the tensor dimensions:

In [14]:
points.shape

torch.Size([3, 2])

Initialize the tensor by providing dimensions as a tuple:

In [15]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

Accessing the elements using two indexes (like in matlab):

In [16]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [17]:
points[0, 1]

tensor(1.)

In [18]:
points[-1, 0]

tensor(2.)

In [19]:
points[0], points[1], points[2]

(tensor([4., 1.]), tensor([5., 3.]), tensor([2., 1.]))

## 3.3 Indexing tensors
Same indexing operators as python lists.

In [20]:
some_list = list(range(6))
some_list

[0, 1, 2, 3, 4, 5]

In [21]:
some_list[:]

[0, 1, 2, 3, 4, 5]

In [22]:
some_list[1:4]

[1, 2, 3]

In [23]:
some_list[1:]

[1, 2, 3, 4, 5]

In [24]:
some_list[:4]

[0, 1, 2, 3]

In [25]:
some_list[:-1]

[0, 1, 2, 3, 4]

In [26]:
some_list[1:4:2]

[1, 3]

Same applies to tensors:

In [27]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [28]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [29]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [30]:
points[1:, 0]

tensor([5., 2.])

In [31]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [32]:
points[None][None]

tensor([[[[4., 1.],
          [5., 3.],
          [2., 1.]]]])

## 3.4 Named tensors
Just like structs, shapes, dicts, tensor labels to each column.

We have an image and we want to convert to grayscale, in this example we use random values because we're lazy. The format if intensities of for each R, G and B channel.

In [33]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]
img_t

tensor([[[-0.4930, -0.8106, -0.5240,  0.0713,  0.1247],
         [ 0.4812,  0.8242, -2.0381,  1.2236, -0.2526],
         [ 0.5561,  0.7216, -1.3518, -0.7476,  0.6972],
         [-1.0888,  1.1922, -0.8258,  1.0155, -0.1985],
         [-1.5539, -0.0048,  1.2896,  1.5456, -1.2595]],

        [[-0.0349,  0.5411,  0.1076, -0.4084,  0.9183],
         [-0.9313, -0.7589, -0.0746,  0.0816, -1.2264],
         [-0.5843,  1.1945,  1.1861, -2.1043,  0.1550],
         [ 0.2470, -0.9824, -1.2079, -1.1832,  0.4047],
         [-0.2835,  0.7244, -0.3604,  0.2474,  0.7030]],

        [[ 1.2969,  2.0338,  2.7685, -1.4814, -0.5952],
         [ 0.5902, -1.2456,  2.3021, -0.2727, -2.2113],
         [-0.4184, -1.5095,  0.9897, -0.7600,  0.5143],
         [-0.0916,  2.7021, -0.0828,  0.0807,  0.6748],
         [-0.5653,  0.0968, -0.8273, -0.8807, -0.6210]]])

To convert to grayscale we use [Luma](https://en.wikipedia.org/wiki/Luma_(video)) to calculate the greyscale.

In [34]:
weights = torch.tensor([0.2126, 0.7152, 0.0722])
weights

tensor([0.2126, 0.7152, 0.0722])

Also, lets suppose we have 2 batches of images, so we have another tensor dimension, the batch.

In [35]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]
batch_t

tensor([[[[-0.7610,  1.1298,  0.6138, -0.6524,  0.2266],
          [-0.7460, -0.6809,  1.2057,  0.4349, -2.7687],
          [-0.9533, -0.3425,  1.8433,  1.7883, -1.8487],
          [-0.9504,  1.2802, -0.1329,  1.0089, -1.2179],
          [ 1.6961, -0.6754, -0.9830, -1.2065, -0.6478]],

         [[ 1.0637,  0.5804,  1.3389, -1.6186,  1.5204],
          [-0.2378,  1.5774, -0.0360, -0.4198, -0.9024],
          [-0.2940, -0.6171, -0.9418, -0.4290, -1.7693],
          [-0.6904,  1.9634,  1.1850,  2.7678, -1.2454],
          [-0.0126,  0.6132, -0.7804, -0.5841, -0.2693]],

         [[ 0.1844, -0.6011,  0.2804,  0.0874, -0.3683],
          [ 1.1970,  0.5687,  1.4343,  0.9489, -0.0914],
          [ 0.3175, -0.8007, -0.6678, -0.2359, -2.1677],
          [ 0.1072, -0.5628,  0.6466,  0.6744, -0.8025],
          [ 0.3714, -0.7287, -1.3414, -1.0329, -0.1620]]],


        [[[ 0.2666, -0.4440, -0.4953, -1.1657, -0.2702],
          [ 0.8494,  0.8494,  0.5698, -0.3463, -1.5398],
          [ 0.3595,  1.

We calculate the means from the last 3 dimensions, because RBG channels are at the end, so we generate a new tensor with the `mean(dim -3, dim -2, dim -1)`

In [36]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive, batch_gray_naive

(tensor([[ 0.2563,  0.5881,  0.7840, -0.6062,  0.1493],
         [ 0.0467, -0.3934,  0.0631,  0.3441, -1.2301],
         [-0.1489,  0.1356,  0.2747, -1.2039,  0.4555],
         [-0.3111,  0.9706, -0.7055, -0.0290,  0.2937],
         [-0.8009,  0.2721,  0.0340,  0.3041, -0.3925]]),
 tensor([[[ 0.1624,  0.3697,  0.7444, -0.7278,  0.4596],
          [ 0.0711,  0.4884,  0.8680,  0.3213, -1.2541],
          [-0.3099, -0.5868,  0.0779,  0.3745, -1.9286],
          [-0.5112,  0.8936,  0.5662,  1.4837, -1.0886],
          [ 0.6850, -0.2636, -1.0349, -0.9412, -0.3597]],
 
         [[-0.2657,  1.1582,  0.3441, -1.9505, -0.1131],
          [ 0.0045,  0.4649,  0.6451, -0.1154, -1.1211],
          [ 0.0621,  0.8548, -0.0606,  0.5422,  0.2822],
          [ 0.3351,  1.3196,  0.2329, -0.6256,  0.5307],
          [-0.2874,  0.3944,  1.4536,  0.1884, -0.4153]]]))

In [37]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [38]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

### Using named tensors for self-documenting code

Specifying dimension names:

In [39]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

C:\Users\bassa\AppData\Local\Temp\ipykernel_4048\2371314847.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at C:\cb\pytorch_1000000000000\work\c10/core/TensorImpl.h:1761.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

Creating new tensors with dimension names from unamed tensors:

In [40]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print('img named:', img_named.shape, img_named.names)
print('batch_named:', batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch_named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


Create a new tensor aligned with the same column/dim ordering by using names to match:

In [41]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

Tensor operations can take a named dimesion as arg:

In [42]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [43]:
gray_named - (img_named*weights_aligned).sum('channels')

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], names=('rows', 'columns'))

Names checking:

In [44]:
gray_named = (img_named[..., :3] * weights_named).sum('channels')

RuntimeError: Error when attempting to broadcast dims ['channels', 'rows', 'columns'] and dims ['channels']: dim 'columns' and dim 'channels' are at the same position from the right but do not match.

Drop named tensors:

In [45]:
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))

## 3.5 Tensor element types

Tensor constructor argument `dtype` specifies the numerical data type of each tensor scalar.

### 3.5.3 Managing a tensor's dtype attribute

In [46]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [47]:
double_points, double_points.dtype, torch.double

(tensor([[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]], dtype=torch.float64),
 torch.float64,
 torch.float64)

In [48]:
short_points, short_points.dtype, torch.int16

(tensor([[1, 2],
         [3, 4]], dtype=torch.int16),
 torch.int16,
 torch.int16)

Using casting functions:

In [49]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()
double_points, short_points

(tensor([[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]], dtype=torch.float64),
 tensor([[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]], dtype=torch.int16))

In [50]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)
double_points, short_points

(tensor([[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]], dtype=torch.float64),
 tensor([[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]], dtype=torch.int16))

Types are converted to the larget type automatically:

In [51]:
points_64 = torch.rand(5, dtype=torch.double)
points_short = points_64.to(torch.short)
points_64 * points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

## 3.6 The tensor API

Use methods from the `torch` module:

In [52]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [53]:
a_t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [54]:
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

Or call methods from the object:

In [55]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [56]:
a_t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [57]:
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

## 3.7 Tensors: Scenic views of storage

Accessing underlying storage by using the `storage()` method of a tensor:

In [58]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

Index directly into storage:

In [59]:
points_storage = points.storage()
points_storage[0]

4.0

In [60]:
points.storage()[1]

1.0

Changing storage value, modifies the tensor also:

In [61]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

### 3.7.2 Modifying stored values: In-place operations

In-place modification operations have an underscore (`_`) suffix, those without underscore always return a new tensor.

In [62]:
a = torch.ones(3, 2)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [63]:
a.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [64]:
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

## 3.8 Tensor metadata: Size, offset, and stride

- **Size:** dimensions, shape
- **Offset:** where is the first element in the storage
- **Stride:** how many storage units we need to skip per dimension to get the next element. 

### 3.8.1 Views of another tensor's storage

In [65]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [66]:
second_point.size()

torch.Size([2])

In [67]:
second_point.shape

torch.Size([2])

To get the stride, we call the `stride()` method:

In [68]:
points.stride()

(2, 1)

We can use the query the `second_point` tensor and see the results:

In [69]:
second_point.size()

torch.Size([2])

In [70]:
second_point.storage_offset()

2

In [71]:
second_point.stride()

(1,)

Changing the subtensor have effect on the initial tensor:

In [72]:
second_point[0] = 10
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

We can clone to prevent modifying the original tensor:

In [73]:
second_point = points[1].clone()
second_point[0] = 20.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

### 3.8.2 Transposing without copying

In [76]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [77]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

Both have the same storage:

In [78]:
id(points.storage()) == id(points_t.storage())

True

Only differ on shape and stride:

In [79]:
points.stride(), points_t.stride()

((2, 1), (1, 2))

### 3.8.3 Transposing in higher dimensions

In [81]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [82]:
transpose_t.shape

torch.Size([5, 4, 3])

In [83]:
some_t.stride()

(20, 5, 1)

In [85]:
transpose_t.stride()

(1, 5, 20)

### 3.8.4 Contiguous tensors

In [86]:
points.is_contiguous()

True

In [87]:
points_t.is_contiguous()

False

Converting a tensor to contiguous:

In [88]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [89]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [90]:
points_t.stride()

(1, 2)

In [91]:
points_t.is_contiguous()

False

In [93]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [94]:
points_t_cont.stride()

(3, 1)

In [95]:
points_t_cont.is_contiguous()

True

In [96]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

## 3.9 Moving tensors to the GPU

### 3.9.1 Managing a tensor's device attribute

In [101]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')
points_gpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')

In [102]:
points_gpu = 2 * points_gpu
points_gpu

tensor([[ 8.,  2.],
        [10.,  6.],
        [ 4.,  2.]], device='cuda:0')

Move back to CPU:

In [104]:
points_cpu = points_gpu.to(device='cpu')
points_cpu

tensor([[ 8.,  2.],
        [10.,  6.],
        [ 4.,  2.]])

## 3.10 NumPy interoperability
Convert to numpy array:

In [105]:
points = torch.ones(3, 4)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [106]:
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

Convert back to torch:

In [108]:
points2 = torch.from_numpy(points_np)
points2

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## 3.12 Serializing tensors

In [109]:
torch.save(points, '../data/ch3/points.t')

In [110]:
points3 = torch.load('../data/ch3/points.t')
points3

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])