# Chapter 3: Pytorch Tensors

### Python Lists

In [3]:
a = [1.0, 2.0, 1.0]
a[2] = 3.0
a

[1.0, 2.0, 3.0]

## 3.1 Constructing tensors

In [4]:
import torch

In [5]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [6]:
a[1]

tensor(1.)

In [7]:
float(a[1])

1.0

In [9]:
a[2] = 2.0
a

tensor([1., 1., 2.])

## 3.2 Anatomy of tensors

Example: store 3 vertices of coords (4,1), (5,3) and (2,1) using a 1D tensor with even-indexes for x and odd-indexes for y coordinate.

In [12]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [13]:
points2 = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points2

tensor([4., 1., 5., 3., 2., 1.])

In [14]:
points == points2

tensor([True, True, True, True, True, True])

In [15]:
points - points2 == torch.zeros(6)

tensor([True, True, True, True, True, True])

In [16]:
points + points2 == 2*points2

tensor([True, True, True, True, True, True])

First coord:

In [17]:
float(points[0]), float(points[1])

(4.0, 1.0)

Storing the coords as a 2D tensor:

In [18]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

To know about the tensor dimensions:

In [19]:
points.shape

torch.Size([3, 2])

Initialize the tensor by providing dimensions as a tuple:

In [21]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

Accessing the elements using two indexes (like in matlab):

In [25]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [26]:
points[0, 1]

tensor(1.)

In [27]:
points[-1, 0]

tensor(2.)

In [29]:
points[0], points[1], points[2]

(tensor([4., 1.]), tensor([5., 3.]), tensor([2., 1.]))

## 3.3 Indexing tensors
Same indexing operators as python lists.

In [39]:
some_list = list(range(6))
some_list

[0, 1, 2, 3, 4, 5]

In [40]:
some_list[:]

[0, 1, 2, 3, 4, 5]

In [41]:
some_list[1:4]

[1, 2, 3]

In [42]:
some_list[1:]

[1, 2, 3, 4, 5]

In [43]:
some_list[:4]

[0, 1, 2, 3]

In [44]:
some_list[:-1]

[0, 1, 2, 3, 4]

In [45]:
some_list[1:4:2]

[1, 3]

Same applies to tensors:

In [47]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [48]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [49]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [50]:
points[1:, 0]

tensor([5., 2.])

In [51]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [52]:
points[None][None]

tensor([[[[4., 1.],
          [5., 3.],
          [2., 1.]]]])

## 3.4 Named tensors
Just like structs, shapes, dicts, tensor labels to each column.

We have an image and we want to convert to grayscale, in this example we use random values because we're lazy. The format if intensities of for each R, G and B channel.

In [56]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]
img_t

tensor([[[-1.1835, -0.7685, -0.7324,  0.8350, -0.1623],
         [ 0.7558,  1.3816, -0.7967,  0.3388, -1.6492],
         [-1.2924,  1.8309, -0.1060,  0.8038, -0.5510],
         [-0.5303, -0.1349,  2.3907,  0.3473,  0.5440],
         [ 0.4286,  0.8241,  0.9571,  0.3551, -0.8520]],

        [[ 1.5612,  0.6536,  0.2390, -3.1533, -1.3207],
         [-0.9403,  0.5684,  0.2527, -0.4097,  1.5437],
         [ 0.1288, -0.9305,  0.3525,  0.0846,  0.5935],
         [-1.7448,  0.5884, -0.1644, -0.3367, -0.0112],
         [-1.8768, -1.2188, -1.1649, -0.6507,  0.2935]],

        [[ 0.5932, -0.4138,  0.1424,  0.2035, -0.8590],
         [ 0.0141,  0.0541,  0.1619,  0.2591,  0.6742],
         [ 0.2784, -0.7470, -0.0204, -1.1171,  1.5238],
         [ 1.2570,  0.3234, -1.0645,  0.5677,  1.3964],
         [-1.5203,  0.2667,  0.8111,  1.0509, -1.5224]]])

To convert to grayscale we use [Luma](https://en.wikipedia.org/wiki/Luma_(video)) to calculate the greyscale.

In [57]:
weights = torch.tensor([0.2126, 0.7152, 0.0722])
weights

tensor([0.2126, 0.7152, 0.0722])

Also, lets suppose we have 2 batches of images, so we have another tensor dimension, the batch.

In [59]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]
batch_t

tensor([[[[ 8.7502e-02, -1.8397e-02, -1.4817e+00,  8.9389e-01,  7.4074e-01],
          [ 2.0379e+00,  1.5996e+00, -4.1546e-01,  9.4662e-01, -9.1306e-01],
          [ 4.6170e-01,  1.2285e+00,  4.5296e-01,  4.8263e-01,  7.2630e-01],
          [ 1.3624e+00, -1.2550e+00,  1.0906e+00, -1.9803e-01, -1.7467e-01],
          [-6.7358e-01,  3.0278e-01,  1.4443e+00,  7.1786e-01, -2.7943e-01]],

         [[-4.2959e-01, -8.0975e-01, -4.9859e-01,  1.0210e+00, -9.9131e-01],
          [-1.3293e+00,  5.1605e-01,  1.7589e+00, -1.8488e+00,  1.4379e+00],
          [ 6.2951e-01, -1.3813e+00,  6.5393e-01,  6.4647e-01,  1.3148e-01],
          [-7.9886e-02, -1.5476e-02, -1.7365e+00,  9.4626e-01,  7.5388e-01],
          [-5.4763e-01,  4.9903e-01, -5.5369e-01,  1.2497e-01, -2.9233e-01]],

         [[-2.8719e-01, -4.9088e-01,  2.3721e-01, -2.1771e+00,  1.1075e+00],
          [ 2.5897e+00,  1.2346e+00, -6.0857e-02,  3.0953e-02, -1.6737e+00],
          [ 1.4982e+00, -1.6663e-01, -7.2700e-01, -4.6998e-01, -4.5466e-

We calculate the means from the last 3 dimensions, because RBG channels are at the end, so we generate a new tensor with the `mean(dim -3, dim -2, dim -1)`

In [60]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive, batch_gray_naive

(tensor([[ 0.3236, -0.1762, -0.1170, -0.7049, -0.7807],
         [-0.0568,  0.6680, -0.1273,  0.0628,  0.1895],
         [-0.2951,  0.0511,  0.0753, -0.0762,  0.5221],
         [-0.3394,  0.2590,  0.3873,  0.1927,  0.6431],
         [-0.9895, -0.0427,  0.2011,  0.2518, -0.6936]]),
 tensor([[[-0.2098, -0.4397, -0.5810, -0.0874,  0.2856],
          [ 1.0994,  1.1168,  0.4275, -0.2904, -0.3830],
          [ 0.8631, -0.1065,  0.1266,  0.2197,  0.1344],
          [ 0.1786, -0.2423, -0.5562, -0.0622,  0.4960],
          [-0.3661,  0.0482,  0.0052, -0.4939, -0.4771]],
 
         [[-1.4812, -0.2877, -0.6861,  0.0163,  0.9263],
          [-0.6189,  0.3150,  0.0260,  0.7064, -0.6071],
          [ 0.9669, -0.4587,  0.7238, -0.0890, -0.5473],
          [-0.1994,  1.2587, -0.3283, -0.2344, -1.2546],
          [-1.2492, -0.2341, -0.5433,  0.4229, -0.4532]]]))