# Chapter 3: Pytorch Tensors

### Python Lists

In [1]:
a = [1.0, 2.0, 1.0]
a[2] = 3.0
a

[1.0, 2.0, 3.0]

## 3.1 Constructing tensors

In [2]:
import torch

In [3]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [4]:
a[1]

tensor(1.)

In [5]:
float(a[1])

1.0

In [6]:
a[2] = 2.0
a

tensor([1., 1., 2.])

## 3.2 Anatomy of tensors

Example: store 3 vertices of coords (4,1), (5,3) and (2,1) using a 1D tensor with even-indexes for x and odd-indexes for y coordinate.

In [7]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [8]:
points2 = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points2

tensor([4., 1., 5., 3., 2., 1.])

In [9]:
points == points2

tensor([True, True, True, True, True, True])

In [10]:
points - points2 == torch.zeros(6)

tensor([True, True, True, True, True, True])

In [11]:
points + points2 == 2*points2

tensor([True, True, True, True, True, True])

First coord:

In [12]:
float(points[0]), float(points[1])

(4.0, 1.0)

Storing the coords as a 2D tensor:

In [13]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

To know about the tensor dimensions:

In [14]:
points.shape

torch.Size([3, 2])

Initialize the tensor by providing dimensions as a tuple:

In [15]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

Accessing the elements using two indexes (like in matlab):

In [16]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [17]:
points[0, 1]

tensor(1.)

In [18]:
points[-1, 0]

tensor(2.)

In [19]:
points[0], points[1], points[2]

(tensor([4., 1.]), tensor([5., 3.]), tensor([2., 1.]))

## 3.3 Indexing tensors
Same indexing operators as python lists.

In [20]:
some_list = list(range(6))
some_list

[0, 1, 2, 3, 4, 5]

In [21]:
some_list[:]

[0, 1, 2, 3, 4, 5]

In [22]:
some_list[1:4]

[1, 2, 3]

In [23]:
some_list[1:]

[1, 2, 3, 4, 5]

In [24]:
some_list[:4]

[0, 1, 2, 3]

In [25]:
some_list[:-1]

[0, 1, 2, 3, 4]

In [26]:
some_list[1:4:2]

[1, 3]

Same applies to tensors:

In [27]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [28]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [29]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [30]:
points[1:, 0]

tensor([5., 2.])

In [31]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [32]:
points[None][None]

tensor([[[[4., 1.],
          [5., 3.],
          [2., 1.]]]])

## 3.4 Named tensors
Just like structs, shapes, dicts, tensor labels to each column.

We have an image and we want to convert to grayscale, in this example we use random values because we're lazy. The format if intensities of for each R, G and B channel.

In [33]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]
img_t

tensor([[[-1.2019,  0.0291,  0.2253,  1.1314, -0.0857],
         [-0.2802,  0.3447, -1.0402,  0.1048,  0.1177],
         [ 0.0358,  0.3354, -0.1171,  0.7412, -0.4129],
         [-1.3866, -0.1343, -0.7752,  0.7502,  1.0500],
         [-0.4012, -0.3991, -0.4020, -1.0559,  1.4396]],

        [[-1.6730,  0.3079,  0.0596, -2.4580, -0.1420],
         [ 1.7095, -0.7220,  0.4074, -1.2165, -0.0279],
         [ 0.3373,  0.2810,  2.5113, -0.9640, -1.1281],
         [ 0.1005,  2.0009,  1.0146,  1.0085, -0.6816],
         [ 1.2192,  1.5790,  1.9703, -0.4926, -0.2932]],

        [[ 0.0572,  2.5672, -1.2032, -1.3472,  0.2408],
         [-1.2340, -0.1913, -2.0520, -0.0620,  1.0775],
         [ 1.7802, -0.3630,  0.2757, -2.5171, -1.0917],
         [ 0.3446, -0.3541,  0.7042, -0.8060,  0.1516],
         [ 1.0678,  1.1950, -1.0627,  0.7912, -1.1572]]])

To convert to grayscale we use [Luma](https://en.wikipedia.org/wiki/Luma_(video)) to calculate the greyscale.

In [34]:
weights = torch.tensor([0.2126, 0.7152, 0.0722])
weights

tensor([0.2126, 0.7152, 0.0722])

Also, lets suppose we have 2 batches of images, so we have another tensor dimension, the batch.

In [35]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]
batch_t

tensor([[[[ 1.9193, -1.9245, -0.1953, -0.6917, -2.5867],
          [ 0.2404, -1.3153,  0.3286, -0.8457,  1.1576],
          [-1.4980,  2.0750, -0.1323,  0.1644, -0.8796],
          [ 1.7223, -0.8358,  0.8544, -2.6090, -0.3685],
          [ 1.5813, -0.7120,  0.7098, -1.2153,  0.4559]],

         [[ 0.5737, -0.5037, -0.3221,  0.2539, -0.0382],
          [-0.6024, -0.8374,  0.1164, -0.9723, -0.4414],
          [ 0.8251,  0.2290, -0.4270, -1.0503, -1.3358],
          [ 0.7316,  1.0266,  1.1822,  1.2336,  0.3796],
          [ 1.6702,  1.3791, -0.7570, -0.8553,  1.0756]],

         [[-0.1027, -0.1253,  0.7635,  0.5333, -1.2850],
          [-1.7556,  1.9921,  1.6188, -0.4864,  0.1538],
          [ 0.9642,  0.4187, -0.3216,  0.3302, -0.5851],
          [-0.3434,  0.1343, -0.1494, -0.4778, -0.7679],
          [ 0.1990,  0.1621, -1.0591,  1.7681,  0.2150]]],


        [[[-0.3129, -1.1529,  1.1229, -1.1357,  1.6548],
          [-0.0112, -2.1223, -0.9160, -1.0034,  0.5047],
          [ 1.4693,  0.

We calculate the means from the last 3 dimensions, because RBG channels are at the end, so we generate a new tensor with the `mean(dim -3, dim -2, dim -1)`

In [36]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive, batch_gray_naive

(tensor([[-0.9393,  0.9680, -0.3061, -0.8913,  0.0044],
         [ 0.0651, -0.1895, -0.8949, -0.3912,  0.3891],
         [ 0.7178,  0.0845,  0.8900, -0.9133, -0.8776],
         [-0.3138,  0.5041,  0.3145,  0.3175,  0.1733],
         [ 0.6286,  0.7917,  0.1685, -0.2524, -0.0036]]),
 tensor([[[ 0.7968, -0.8512,  0.0820,  0.0318, -1.3033],
          [-0.7059, -0.0535,  0.6879, -0.7681,  0.2900],
          [ 0.0971,  0.9076, -0.2937, -0.1852, -0.9335],
          [ 0.7035,  0.1084,  0.6291, -0.6177, -0.2522],
          [ 1.1502,  0.2764, -0.3688, -0.1009,  0.5822]],
 
         [[ 0.2027,  0.4551,  0.2850, -0.4046,  0.6053],
          [ 0.8047, -0.8888, -0.3858, -0.2093, -0.6425],
          [ 0.3116,  0.2446, -0.2249,  0.1826,  0.2903],
          [ 0.2164, -0.2912, -0.7397,  0.4649, -0.8735],
          [ 0.1996, -0.0219,  1.2818, -0.2946,  0.6492]]]))

In [37]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [38]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

### Using named tensors for self-documenting code

Specifying dimension names:

In [39]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

C:\Users\bassa\AppData\Local\Temp\ipykernel_9956\2371314847.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at C:\cb\pytorch_1000000000000\work\c10/core/TensorImpl.h:1761.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

Creating new tensors with dimension names from unamed tensors:

In [40]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print('img named:', img_named.shape, img_named.names)
print('batch_named:', batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch_named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


Create a new tensor aligned with the same column/dim ordering by using names to match:

In [41]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

Tensor operations can take a named dimesion as arg:

In [42]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [43]:
gray_named - (img_named*weights_aligned).sum('channels')

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], names=('rows', 'columns'))

Names checking:

In [52]:
gray_named = (img_named[..., :3] * weights_named).sum('channels')

RuntimeError: Error when attempting to broadcast dims ['channels', 'rows', 'columns'] and dims ['channels']: dim 'columns' and dim 'channels' are at the same position from the right but do not match.

Drop named tensors:

In [45]:
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))

## 3.5 Tensor element types

Tensor constructor argument `dtype` specifies the numerical data type of each tensor scalar.

### 3.5.3 Managing a tensor's dtype attribute

In [46]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [47]:
double_points, double_points.dtype, torch.double

(tensor([[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]], dtype=torch.float64),
 torch.float64,
 torch.float64)

In [48]:
short_points, short_points.dtype, torch.int16

(tensor([[1, 2],
         [3, 4]], dtype=torch.int16),
 torch.int16,
 torch.int16)

Using casting functions:

In [49]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()
double_points, short_points

(tensor([[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]], dtype=torch.float64),
 tensor([[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]], dtype=torch.int16))

In [50]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)
double_points, short_points

(tensor([[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]], dtype=torch.float64),
 tensor([[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]], dtype=torch.int16))

Types are converted to the larget type automatically:

In [51]:
points_64 = torch.rand(5, dtype=torch.double)
points_short = points_64.to(torch.short)
points_64 * points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)